### ISSUE TITLE
[1.0-beta1] Unable to access agent httpd interface after remote installation

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi-agent#29]
### Bug reporting acknowledgment

- [X] Yes, I read it

### Professional support

Yes, I know

### Describe the bug

I don't know if it's the msi problem - when I install fusioninventory-agent - it works. The service does not start with glpi-agent and I do not have an answer by http.

And BTW. In file glpi-agent-packaging.pl:
`$result .= $ident ."  ". qq[  <RegistryKey Root="HKLM" Key="Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\[ProductCode]">\n];`
But in .vbs:
`strCurrentSetupVersion = WshShell.RegRead("HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\GLPI-Agent\DisplayVersion")`

Checking if the subkey exist in vbs will always fail because DisplayVersion is in: Uninstall\\{FA01074A-6BF8-1014-B0E8-F9F8208C43AB}

### To reproduce

1. First try with psexec:

`psexec.exe \\computername -s msiexec.exe /i "\\computername\c$\temp\glpi-agent-1.0-beta1-x64.msi" RUNNOW=1 EXECMODE=service NO_SSL_CHECK=1 HTTPD_TRUST=192.168.1.11 HTTPD_PORT=61111 SERVER='https://server.com/plugins/fusioninventory/' LOGFILE='C:\GLPI\glpi-agent.log' LOCAL='C:\GLPI\' /quiet`

2. Second try with vbs - setup option like before.

### Expected behavior

It would be nice to get a reply over http

http://computername:61111

### Operating system

Windows

### GLPI Agent version

1.0-beta1

### GLPI version

9.5.6

### FusionInventory for GLPI version

9.5+3.0

### Additional context

Agent installed correctly (except for the no-service issue). It communicates with the server without errors. But I need ToolBox :)

Installation using the graphical interface does not cause this problem.

**Comment by WebGregGit** [comment]
Sometimes I should go to sleep too... 

Probably not EXECMODE=service but EXECMODE=1. I was suggested by #15.
I'll check it in a few hours.

**Comment by WebGregGit** [comment]
I confirm, it's not a bug but my mistake.

With **_EXECMODE=1_** works perfect.

Sorry.

**Comment by g-bougard** [comment]
Hi @WebGregGit 

yes, EXECMODE=1 is the right syntax. Thank you to have finally find your way but you would have found it more quickly following the official documentation: [GLPI Agent Windows command line installation](https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html) ;-)

Anyway, thank you yo have find the registry problem as you're definitively right on that point and I'll fix it for next release.

Last point, "ToolBox" should be used to talk about an agent httpd plugin which is disabled by default and only useful in really specific usage, you should just have to talk about "agent httpd interface".

Best regards

**Comment by g-bougard** [comment]
I fixed the packaging and vbs accordingly to your remark. Can you confirm the [vbs](https://raw.githubusercontent.com/glpi-project/glpi-agent/develop/contrib/windows/glpi-agent-deployment.vbs) is now working as expected ?

**Comment by WebGregGit** [comment]
@g-bougard

Thank you for your answer.

No, there is still a problem with that. You have changed to {2D867E73-6BF5-1014-BC86-AD002C3B00E0}.
But in my installation it is {FA01074A-6BF8-1014-B0E8-F9F8208C43AB}
I have 1.0-beta1. 

In file https://github.com/glpi-project/glpi-agent/blob/develop/contrib/windows/glpi-agent-packaging.pl#L465 I found:

`                $result .= $ident ."  ". qq[  <RegistryKey Root="HKLM" Key="Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\[ProductCode]">\n];
`

Maybe it would be better to change it to:

`                $result .= $ident ."  ". qq[  <RegistryKey Root="HKLM" Key="Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\glpi-agent">\n];`

? I suspect that the product key will change depending on the installation.

**Comment by g-bougard** [comment]
Hi @WebGregGit 
`2D867E73-6BF5-1014-BC86-AD002C3B00E0` is ProductCode for x86 (32bits) GLPI Agent release.
`FA01074A-6BF8-1014-B0E8-F9F8208C43AB` is ProductCode for x64 (64bits) GLPI Agent release.
So this is what I'm checking in vbs now. Did you made a test or just read the code and first found x86 GUID without checking the check is different on x64 GUID ?

**Comment by WebGregGit** [comment]
Hello @g-bougard 

I'm sorry I wasn't careful enough. 
I do not have other version than https://github.com/glpi-project/glpi-agent/releases/download/1.0-beta1/GLPI-Agent-1.0-beta1-x64.msi
Just tried to change the registry value for DisplayVersion (I set 0.0.1)

SetupVersion = "1.0-beta1"
SetupLocation = "https://github.com/glpi-project/glpi-agent/releases/download/" & SetupVersion

After run vbs I checked DisplayVersion - still 0.0.1. I assumed that if it worked, it would have reinstalled by setting the value to 1.0.0. However, this did not happen. But it could be my fault.


BTW. The old path was left in the comments:
"The subkey SOFTWARE \ Microsoft \ Windows \ CurrentVersion \ Uninstall \ GLPI-Agent exists"

**Comment by g-bougard** [comment]
Hi @WebGregGit 
thanks to your remarks, I finally deeply reworked GLPI Agent windows packaging and deployment vbs.
Starting with `1.0-gitf9889dfe` nightly build, it should work as expected.
Here is a list of what was essentially changed:
* Packaging:
  * Installer now register its dedicated configuration into `HK_LM\SOFTWARE\GLPI-Agent\Installer`
  * It also store there the installed version into the `Version` key
  * I also setup the packaging to permit downgrade
  * ProductName nows contains version and tag, so it's easy to identify current installed version in application list
* Deployment VBS:
  * It checks the installed version checking `HK_LM\SOFTWARE\GLPI-Agent\Installer\Version` registry key
  * It better use `MsiExec.exe` to install the msi package
  * I renamed `Force` option to `Repair`
  * When installing, it uses `/i` option of msiexec and `/fa` when repairing
  * It can also download from nightly builds site if `SetupVersion` matches `-(git[0-9a-f]{8})$` regexp (finish with -gitABCDWXYZ where A,B,C,D,W,X,Y,Z are lower-case hex-digits like in `1.0-gitf9889dfe`)
