### ISSUE TITLE
No inventory in GLPI 10

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi-agent#60]
Hi @g-bougard 

I see a new problem with the agent:

I decided to deploy to multiple computers. (Same brand, model and configuration). Installing the agent manually (same agent, same version). On some computer everything is OK, inventory without problem. On others the agent goes up in GLPI but does not make any inventory. We don't even see the version of the agent. 

The agent is present but the pc does not go up

Here log : 

```
[Mon Jan 31 09:44:59 2022][info] GLPI Agent service starting
[Mon Jan 31 09:45:00 2022][info] [http server] HTTPD service started on port 62354
[Mon Jan 31 09:45:01 2022][info] GLPI Agent memory usage: WSS=3764224 PFU=104599552
[Mon Jan 31 09:45:01 2022][info] target server0: server https://glpi.SERVEUR/front/inventory.php
[Mon Jan 31 09:45:01 2022][info] sending prolog request to server0
[Mon Jan 31 09:45:01 2022][info] server0 answer shows it supports GLPI Agent protocol
[Mon Jan 31 09:45:08 2022][info] running task Inventory
[Mon Jan 31 09:45:08 2022][info] New inventory from LAPTOPFAILINVENTORY-2022-01-31-09-44-59 for server0
[Mon Jan 31 09:47:55 2022][info] GLPI Agent memory usage: WSS=3350528 PFU=165687296
[Mon Jan 31 09:48:18 2022][info] sending contact request to server0
[Mon Jan 31 09:48:22 2022][info] running task Inventory
[Mon Jan 31 09:48:22 2022][info] New inventory from LAPTOPFAILINVENTORY-2022-01-31-09-44-59 for server0
[Mon Jan 31 09:49:00 2022][info] GLPI Agent memory usage: WSS=3350528 PFU=168800256
```

![brave_eMxY0BOuR9](https://user-images.githubusercontent.com/6154697/151766255-27ab81bc-b24f-47fe-8851-cff41feffaf1.jpg)

_Originally posted by @Deki60 in https://github.com/glpi-project/glpi-agent/issues/42#issuecomment-1025516268_

**Comment by g-bougard** [comment]
Hi @Deki60

in that case, you should first enable **debug2** on agent side. For that edit the `debug` key in registry at `HK_LM\Software\GLPI-Agent` setting it to `2`, restart the agent service and force an inventory run.

You should probably obtain an error from the server showing a JSON Error.

But in that case, you should also try a [nightly build](https://nightly.glpi-project.org/glpi-agent) as we should have fixed most cases since 1.0.

**Comment by Deki60** [comment]
I come back ASAP with the answer. i will try with a nighlty agent

**Comment by g-bougard** [comment]
Hi @Deki60 
you can even try with [GLPI-Agent v1.1](https://github.com/glpi-project/glpi-agent/releases/tag/1.1) I released this morning.

**Comment by Deki60** [comment]
Hi @g-bougard 

the display on GLPI still does not indicate the version of the agent but the inventory is now done correctly with version 1.1 thank you

**Comment by g-bougard** [comment]
Hi @Deki60 
thank you for your feedback.
About the version not displayed problem, can you confirm which page is concerned ? And can you check the `php-errors.log` file on server-side for any new message at the same time to load the page ?
Actually, I can't reproduce that problem.

**Comment by Deki60** [comment]
sorry it's correct GLPI just took a while to refresh the information the version of the agent is correctly indicated

**Comment by g-bougard** [comment]
Okay, maybe you see this problem because an inventory is being submitted and the server only updates this information after the inventory has been imported.
