### ISSUE TITLE
RustDesk ID scan break with new RustDesk 1.2.3-1

### ISSUE THREAD

**Issue by NicoUnterburger** [glpi-project/glpi-agent#609]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

With new Rustdesk Version "1.2.3-1"  glpi-agent cant receive the ID. 
I thin Problem is the new "-1" on Version, which cant veriffied by GLPI, so the Script will break up.

If I remove the Version check in [RustDesk.pm, line 48-54](https://github.com/glpi-project/glpi-agent/blob/develop/lib/GLPI/Agent/Task/Inventory/Generic/Remote_Mgmt/RustDesk.pm), the ID is transferred correct. 

### To reproduce

Install actual RustDesk-Agent (1.2.3-1) and try to collect inventory. 
Result: Can't get RustDesk ID, RustDesk is probably not running

### Expected behavior

Can view the RustDesk-ID in GLPI-Dashboard

### Operating system

Windows

### GLPI Agent version

1.7

### GLPI version

10.0.12

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.3.4

**Comment by g-bougard** [comment]
Hi @NicoUnterburger 

you're probably right and I'm afraid people codes simple stuffs in a so much weird way in that project...

Can you share the output of the following command run to be sure to include the right fix ?
```
"C:\Program Files\RustDesk\rustdesk.exe" --version
```

**Comment by NicoUnterburger** [comment]
Hi @g-bougard 
here you find the output of the above command: 

PS C:\Program Files\RustDesk> .\rustdesk.exe --version
PS C:\Program Files\RustDesk> .\rustdesk.exe --version | out-host
1.2.3-1

**Comment by g-bougard** [comment]
Hi @NicoUnterburger 

thank you for that sharing, the next nightly build should include the fix I just pushed.

**Comment by mmarodin** [comment]
There is still the same issue using the new 1.7.2 glpi-agent.
Could you fix it? :)
Thanks

**Comment by g-bougard** [comment]
Hello @mmarodin 

that issue is fixed in [nightlies](https://nightly.glpi-project.org/glpi-agent/) and 1.7.2 is just a security fix regarding 1.7.1. This means the next release including this fix will be 1.8 version. That version should be released in few weeks.
