### ISSUE TITLE
Windows Defender AV not detected on Windows Server

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi-agent#857]
> i don't know if this was supposed to fix the inventory of Windows Defender antivirus on Windows servers as well, but i can tell you that i am still not able to get the Windows Defender from my Windows Servers machine on the inventory.
> i am a bit confused, but maybe i don't understand what parameter needs to be present in the server in order to have Defender detected, but i've checked in my server and i can see the following registry key present:
> Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Signature Updates\ASSignatureVersion
> 
> Isn't this enough for the agent to inventory the Windows defender installation in the Server?
> 
> Thanks in advance for your help.
>  

 _Originally posted by @lexcyr in [#565](https://github.com/glpi-project/glpi-agent/issues/565#issuecomment-2657730928)_

**Comment by g-bougard** [comment]
Hi @lexcyr

about Windows Defender, as there's not generic way to detect AV like on Windows Desktop, we have to add a dedicated detection.

To do so, can you share the output of the following command so I can identify how Defender service is registered on Windows Server ?
```
wmic path Win32_Service get /format:list
```

Can you also share an export of `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Signature Updates` registry key ?

**Comment by lexcyr** [comment]
Hello @g-bougard 
you can find the information here:
**HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Signature Updates**
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Signature Updates]
"EngineVersion"="1.1.24090.11"
"AVSignatureVersion"="1.421.1876.0"
"AVSignatureBaseVersion"="1.421.0.0"
"AVSignatureApplied"=hex:80,e8,e8,6f,06,7e,db,01
"ASSignatureVersion"="1.421.1876.0"
"ASSignatureBaseVersion"="1.421.0.0"
"ASSignatureApplied"=hex:80,15,1a,71,06,7e,db,01
"SignatureLocation"="C:\\ProgramData\\Microsoft\\Windows Defender\\Definition Updates\\{BDE85E80-3915-3648-B279-9E2CC51EF5EB}"
"SignatureType"=dword:00000000
"SignatureUpdateLastAttempted"=hex:9f,d2,bb,73,b6,7e,db,01
"SignatureUpdatePending"=dword:00000000
"LastFallbackTime"=hex:39,69,c3,73,b6,7e,db,01
"DisableDefaultSigs"=dword:00000000
"SignatureCategoryID"="8c3fcc84-3589-4a95-8b89-a166a86217486"
"SignatureUpdateCount"=dword:00000043
"SignaturesLastUpdated"=hex:39,78,9e,6d,73,7e,db,01
"MoCAMPUpdateStarted"=hex:68,9f,74,fd,0c,62,db,01
"EnableUpdateResiliency"=dword:00000000
"LastEmergencySigCheck"=hex:0e,1c,89,9f,e0,7e,db,01
"ISUInterval"=dword:00000004
"ISULength"=dword:00000018
"ISUReason"=dword:00000010
"ISUControlFlags"=dword:00000001
```

**wmic**: [wmi.txt](https://github.com/user-attachments/files/18799664/wmi.txt)

**Comment by g-bougard** [comment]
Thank you @lexcyr,

I'm preparing an update, but do you have also an output for this command ?
```
wmic /namespace:\\root\microsoft\windows\defender path MSFT_MpComputerStatus get /format:list
```

**Comment by lexcyr** [comment]
Thanks a lot, i am looking forward to test that update.

```
/namespace:\\root\microsoft\windows\defender path MSFT_MpComputerStatus get /format:list

AMEngineVersion=1.1.24090.11
AMProductVersion=4.18.24090.11
AMRunningMode=Normal
AMServiceEnabled=TRUE
AMServiceVersion=4.18.24090.11
AntispywareEnabled=TRUE
AntispywareSignatureAge=1
AntispywareSignatureLastUpdated=20250213110007.000000+000
AntispywareSignatureVersion=1.421.1876.0
AntivirusEnabled=TRUE
AntivirusSignatureAge=1
AntivirusSignatureLastUpdated=20250213110005.000000+000
AntivirusSignatureVersion=1.421.1876.0
BehaviorMonitorEnabled=TRUE
ComputerID=SDG85W5-46CB-D7E8-32597462841C
ComputerState=0
DefenderSignaturesOutOfDate=FALSE
DeviceControlDefaultEnforcement=
DeviceControlPoliciesLastUpdated=16010101000000.000000+000
DeviceControlState=Disabled
FullScanAge=4294967295
FullScanEndTime=
FullScanOverdue=FALSE
FullScanRequired=FALSE
FullScanSignatureVersion=
FullScanStartTime=
InitializationProgress=ServiceStartedSuccessfully
IoavProtectionEnabled=TRUE
IsTamperProtected=TRUE
IsVirtualMachine=TRUE
LastFullScanSource=0
LastQuickScanSource=2
NISEnabled=TRUE
NISEngineVersion=1.1.24090.11
NISSignatureAge=1
NISSignatureLastUpdated=20250213110005.000000+000
NISSignatureVersion=1.421.1876.0
OnAccessProtectionEnabled=TRUE
ProductStatus=524288
QuickScanAge=0
QuickScanEndTime=20250214102241.538000+000
QuickScanOverdue=FALSE
QuickScanSignatureVersion=1.421.1876.0
QuickScanStartTime=20250214102041.817000+000
RealTimeProtectionEnabled=TRUE
RealTimeScanDirection=0
RebootRequired=FALSE
SmartAppControlExpiration=
SmartAppControlState=Off
TamperProtectionSource=ATP
TDTCapable=N/A
TDTMode=N/A
TDTSiloType=N/A
TDTStatus=N/A
TDTTelemetry=N/A
TroubleShootingDailyMaxQuota=480
TroubleShootingDailyQuotaLeft=480
TroubleShootingEndTime=INFINITE
TroubleShootingExpirationLeft=INFINITE
TroubleShootingMode=Disabled
TroubleShootingModeSource=Service
TroubleShootingQuotaResetTime=N/A
TroubleShootingStartTime=N/A
```

**Comment by g-bougard** [comment]
Hi @lexcyr 

thank you for the shared datas.

I just pushed an update which should permit to handle Microsoft Defender enabled on Windows Server. You'll be able to test it with next nightly build from https://nightly.glpi-project.org/glpi-agent/.

**Comment by lexcyr** [comment]
Hello @g-bougard ,
i have tested with the latest nightly build, and i am still not able to have Defender found in the server.
Here is my config:
glpi-agent: GLPI-Agent v1.13-git4895a6ba
Glpi-server: 10.0.17

**Comment by g-bougard** [comment]
Hi @lexcyr 

I just fixed an issue which can make inventory task not working as expected on windows. Can you test with the development build from this GH Actions run: https://github.com/glpi-project/glpi-agent/actions/runs/13371371219
Just download the "Windows-Build-x64" zip archive artifact and you'll find the installer into it.

If the problem is not fixed with that version, can you share the output of the following command run from an administrative console and from glpi-agent installation folder ?
```
glpi-inventory --debug --debug --partial=antivirus
```

**Comment by lexcyr** [comment]
With that build i am able to get the antivirus now. Good Job !!!
But there are some information missing like the "Antivirus version", "Signature database version" and the "up to date".
I thought thoses information was present somewhere is the dataset i've shared with you.

![Image](https://github.com/user-attachments/assets/23409c49-a93d-49ff-8768-6ea56c6d3864)

**Comment by g-bougard** [comment]
Okay, can you share the output of the command I gave just before ?

**Comment by lexcyr** [comment]
Oups, i've forgot to add it.
Here we go
```
c:\Program Files\GLPI-Agent>glpi-inventory --debug --debug --partial=antivirus
[info] New inventory from TESTVM-2025-02-17-09-12-03 for local0
[debug2] module GLPI::Agent::Task::Inventory::AIX disabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::Bios disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::CPU disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::Controllers disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::Drives disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::Hardware disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::LVM disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::Memory disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::Modems disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::Networks disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::OS disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::Slots disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::Softwares disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::Sounds disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::Storages disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2]   GLPI::Agent::Task::Inventory::AIX::Videos disabled: implicit dependency GLPI::Agent::Task::Inventory::AIX not enabled
[debug2] module GLPI::Agent::Task::Inventory::AccessLog disabled: 'accesslog' category disabled
[debug2] module GLPI::Agent::Task::Inventory::BSD disabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::Alpha disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD not enabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::CPU disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD not enabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::Drives disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD not enabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::MIPS disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD not enabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::Memory disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD not enabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::Networks disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD not enabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::OS disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD not enabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::SPARC disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD not enabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::Softwares disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD not enabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::Storages disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD not enabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::Storages::Megaraid disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD::Storages not enabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::Uptime disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD not enabled
[debug2]   GLPI::Agent::Task::Inventory::BSD::i386 disabled: implicit dependency GLPI::Agent::Task::Inventory::BSD not enabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Arch disabled: 'os' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Batteries disabled: 'battery' category disabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Batteries::Acpiconf disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Batteries not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Batteries::SysClass disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Batteries not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Batteries::Upower disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Batteries not enabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Databases disabled: 'database' category disabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Databases::DB2 disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Databases not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Databases::MSSQL disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Databases not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Databases::MongoDB disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Databases not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Databases::MySQL disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Databases not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Databases::Oracle disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Databases not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Databases::PostgreSQL disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Databases not enabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Dmidecode::Battery disabled: 'battery' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Dmidecode::Memory disabled: 'memory' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Dmidecode::Ports disabled: 'port' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Dmidecode::Psu disabled: 'psu' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Dmidecode::Slots disabled: 'slot' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Domains disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Drives disabled: 'drive' category disabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Drives::ASM disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Drives not enabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Environment disabled: 'environment' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Firewall disabled: 'firewall' category disabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Firewall::Systemd disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Firewall not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Firewall::Ufw disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Firewall not enabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Hostname disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Ipmi disabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Ipmi::Fru disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Ipmi not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Ipmi::Fru::Controllers disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Ipmi::Fru not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Ipmi::Fru::Memory disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Ipmi::Fru not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Ipmi::Fru::Psu disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Ipmi::Fru not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Ipmi::Lan disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Ipmi not enabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Networks disabled: 'network' category disabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Networks::iLO disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Networks not enabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::OS disabled: 'os' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::PCI disabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::PCI::Controllers disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::PCI not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::PCI::Modems disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::PCI not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::PCI::Sounds disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::PCI not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::PCI::Videos disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::PCI not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::PCI::Videos::Nvidia disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::PCI::Videos not enabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Printers disabled: 'printer' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Processes disabled: 'process' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt disabled: 'remote_mgmt' category disabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt::AnyDesk disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt::LiteManager disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt::MeshCentral disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt::RMS disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt::RustDesk disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt::SupRemo disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt::TacticalRMM disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt::TeamViewer disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt not enabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Rudder disabled: 'rudder' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::SSH disabled: 'os' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Screen disabled: 'monitor' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Softwares disabled: 'software' category disabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Softwares::Deb disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Softwares not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Softwares::Flatpak disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Softwares not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Softwares::Gentoo disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Softwares not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Softwares::Nix disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Softwares not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Softwares::Pacman disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Softwares not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Softwares::RPM disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Softwares not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Softwares::Slackware disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Softwares not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Softwares::Snap disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Softwares not enabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Storages disabled: 'storage' category disabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Storages::3ware disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Storages not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Storages::HP disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Storages not enabled
[debug2]   GLPI::Agent::Task::Inventory::Generic::Storages::HpWithSmartctl disabled: implicit dependency GLPI::Agent::Task::Inventory::Generic::Storages not enabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Timezone disabled: 'os' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::USB disabled: 'usb' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Generic::Users disabled: 'user' category disabled
[debug2] module GLPI::Agent::Task::Inventory::HPUX disabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::Bios disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::CPU disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::Controllers disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::Drives disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::Hardware disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::MP disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::Memory disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::Networks disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::OS disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::Slots disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::Softwares disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::Storages disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2]   GLPI::Agent::Task::Inventory::HPUX::Uptime disabled: implicit dependency GLPI::Agent::Task::Inventory::HPUX not enabled
[debug2] module GLPI::Agent::Task::Inventory::Linux disabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::ARM disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::ARM::Board disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::ARM not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::ARM::CPU disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::ARM not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Alpha disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Alpha::CPU disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::Alpha not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::AntiVirus disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::AntiVirus::Bitdefender disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::AntiVirus not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::AntiVirus::Cortex disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::AntiVirus not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::AntiVirus::Defender disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::AntiVirus not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::AntiVirus::Sentinelone disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::AntiVirus not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Bios disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Distro disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Distro::NonLSB disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::Distro not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Distro::OSRelease disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::Distro not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Drives disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Hardware disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Inputs disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::LVM disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::MIPS disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::MIPS::CPU disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::MIPS not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Memory disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Networks disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Networks::DockerMacvlan disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::Networks not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Networks::FibreChannel disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::Networks not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::OS disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::PowerPC disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::PowerPC::Bios disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::PowerPC not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::PowerPC::CPU disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::PowerPC not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::SPARC disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::SPARC::CPU disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::SPARC not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Storages disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Storages::Adaptec disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::Storages not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Storages::Lsilogic disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::Storages not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Storages::Megacli disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::Storages not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Storages::MegacliWithSmartctl disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::Storages not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Storages::Megaraid disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::Storages not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Storages::ServeRaid disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::Storages not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Uptime disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::Videos disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::i386 disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::i386::CPU disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::i386 not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::m68k disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux not enabled
[debug2]   GLPI::Agent::Task::Inventory::Linux::m68k::CPU disabled: implicit dependency GLPI::Agent::Task::Inventory::Linux::m68k not enabled
[debug2] module GLPI::Agent::Task::Inventory::MacOS disabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::AntiVirus disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::AntiVirus::Cortex disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS::AntiVirus not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::AntiVirus::Defender disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS::AntiVirus not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::AntiVirus::SentinelOne disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS::AntiVirus not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Batteries disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Bios disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::CPU disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Drives disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Firewall disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Hardware disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Hostname disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::License disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Memory disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Networks disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::OS disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Printers disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Psu disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Softwares disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Sound disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Storages disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::USB disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Uptime disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2]   GLPI::Agent::Task::Inventory::MacOS::Videos disabled: implicit dependency GLPI::Agent::Task::Inventory::MacOS not enabled
[debug2] module GLPI::Agent::Task::Inventory::Provider disabled: 'provider' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Solaris disabled
[debug2]   GLPI::Agent::Task::Inventory::Solaris::Bios disabled: implicit dependency GLPI::Agent::Task::Inventory::Solaris not enabled
[debug2]   GLPI::Agent::Task::Inventory::Solaris::CPU disabled: implicit dependency GLPI::Agent::Task::Inventory::Solaris not enabled
[debug2]   GLPI::Agent::Task::Inventory::Solaris::Controllers disabled: implicit dependency GLPI::Agent::Task::Inventory::Solaris not enabled
[debug2]   GLPI::Agent::Task::Inventory::Solaris::Drives disabled: implicit dependency GLPI::Agent::Task::Inventory::Solaris not enabled
[debug2]   GLPI::Agent::Task::Inventory::Solaris::Hardware disabled: implicit dependency GLPI::Agent::Task::Inventory::Solaris not enabled
[debug2]   GLPI::Agent::Task::Inventory::Solaris::Memory disabled: implicit dependency GLPI::Agent::Task::Inventory::Solaris not enabled
[debug2]   GLPI::Agent::Task::Inventory::Solaris::Networks disabled: implicit dependency GLPI::Agent::Task::Inventory::Solaris not enabled
[debug2]   GLPI::Agent::Task::Inventory::Solaris::OS disabled: implicit dependency GLPI::Agent::Task::Inventory::Solaris not enabled
[debug2]   GLPI::Agent::Task::Inventory::Solaris::Slots disabled: implicit dependency GLPI::Agent::Task::Inventory::Solaris not enabled
[debug2]   GLPI::Agent::Task::Inventory::Solaris::Softwares disabled: implicit dependency GLPI::Agent::Task::Inventory::Solaris not enabled
[debug2]   GLPI::Agent::Task::Inventory::Solaris::Storages disabled: implicit dependency GLPI::Agent::Task::Inventory::Solaris not enabled
[debug2] module GLPI::Agent::Task::Inventory::Virtualization disabled: 'virtualmachine' category disabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::Docker disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::Hpvm disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::HyperV disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::Jails disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::Libvirt disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::Lxc disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::Lxd disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::Parallels disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::Qemu disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::SolarisZones disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::SystemdNspawn disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::VirtualBox disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::Virtuozzo disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::VmWareDesktop disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::VmWareESX disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::Vserver disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::Wsl disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::Xen disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2]   GLPI::Agent::Task::Inventory::Virtualization::XenCitrixServer disabled: implicit dependency GLPI::Agent::Task::Inventory::Virtualization not enabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Batteries disabled: 'battery' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::CPU disabled: 'cpu' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Controllers disabled: 'controller' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Drives disabled: 'drive' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Environment disabled: 'environment' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Firewall disabled: 'firewall' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Inputs disabled: 'input' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::License disabled: 'licenseinfo' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Memory disabled: 'memory' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Modems disabled: 'modem' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Networks disabled: 'network' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::OS disabled: 'os' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Ports disabled: 'port' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Printers disabled: 'printer' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Registry disabled: 'registry' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Slots disabled: 'slot' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Softwares disabled: 'software' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Sounds disabled: 'sound' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Storages disabled: 'storage' category disabled
[debug2]   GLPI::Agent::Task::Inventory::Win32::Storages::HP disabled: implicit dependency GLPI::Agent::Task::Inventory::Win32::Storages not enabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::USB disabled: 'usb' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Users disabled: 'user' category disabled
[debug2] module GLPI::Agent::Task::Inventory::Win32::Videos disabled: 'video' category disabled
[debug] module GLPI::Agent::Task::Inventory::Win32::Bios disabled because of GLPI::Agent::Task::Inventory::Generic::Dmidecode::Bios
[debug] Running GLPI::Agent::Task::Inventory::Generic
[debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode
[debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Bios
[debug2] executing dmidecode
[debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Hardware
[debug2] executing dmidecode
[debug] Running GLPI::Agent::Task::Inventory::Win32
[debug] Running GLPI::Agent::Task::Inventory::Win32::Hardware
[debug] Running GLPI::Agent::Task::Inventory::Vmsystem
[debug] Running GLPI::Agent::Task::Inventory::Win32::AntiVirus
[debug2] Looking for Win32_Service class WMI objects
[debug2] Added Windows Defender
[debug] Running GLPI::Agent::Task::Inventory::Win32::Chassis
{
   "action": "inventory",
   "content": {
      "antivirus": [
         {
            "enabled": true,
            "name": "Windows Defender"
         }
      ],
      "bios": {
         "bdate": "2020-11-12",
         "bmanufacturer": "Phoenix Technologies LTD",
         "bversion": "6.00",
         "mmanufacturer": "Intel Corporation",
         "mmodel": "440BX Desktop Reference Platform",
         "smanufacturer": "VMware, Inc.",
         "smodel": "VMware Virtual Platform",
         "ssn": "VMware-42 18 16 91 c6 f3 93 8d-fe 95 8e 3e 6a 74 ca a0"
      },
      "hardware": {
         "chassis_type": "Other",
         "memory": 4095,
         "name": "TESTVM",
         "uuid": "91161842-F3C6-8D93-FE95-8E3E6A74CAA0",
         "vmsystem": "VMware",
         "winlang": "1033",
         "winowner": "Windows User",
         "winprodid": "00454-10000-00001-AA267",
         "winprodkey": "VDYBN-UEMD--HYEN7D",
         "workgroup": "WORKGROUP"
      },
      "versionclient": "GLPI-Inventory_v1.13-gite98b1811"
   },
   "deviceid": "TESTVM-2025-02-17-09-12-03",
   "itemtype": "Computer",
   "partial": true
}
[info] Inventory dumped on standard output

c:\Program Files\GLPI-Agent>

```

**Comment by g-bougard** [comment]
Okay I pushed a fix in c79662158

Can you test the new build from https://github.com/glpi-project/glpi-agent/actions/runs/13374898617 or next nightly build ?

**Comment by lexcyr** [comment]
it seems correct now.
thank you so much

![Image](https://github.com/user-attachments/assets/763d5187-820b-41a8-a388-67d03544f4c2)
