### ISSUE TITLE
Docker VmSystem detected as VirtualBox

### ISSUE THREAD

**Issue by hramosmo** [glpi-project/glpi-agent#979]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

When the inventory is executed inside a Docker container that is itself running within a VirtualBox virtual machine, the system reports the VMsystem as "virtualbox" instead of "docker". Upon reviewing the code, I noticed that in the file lib/GLPI/Agent/Task/Inventory/Vmsystem.pm, there is a section (lines 297–299) that attempts to detect if the environment is Docker, but this check is performed after verifying for VirtualBox, QEMU, Hyper-V, etc.

Wouldn't it make more sense to check for Docker first, similar to how the detection is handled for LXC? This issue causes the UUID returned to be that of the host machine rather than one specific to the Docker container.

### To reproduce

Run glpi-inventory inside Docker Containter running on Virtualbox Machine.

### Expected behavior

Return "Vmsystem: Docker" and uuid of Docker

### Operating system

Linux

### GLPI Agent version

v1.15

### GLPI version

10.0.18

### Additional context

I'm generating inventory offline and then injecting with Glpi-injector

**Comment by g-bougard** [comment]
Hi @hramosmo 

thank you for your contribution.

Your explanation make sens. I just pushed a fix moving the lines you pointed before the detection of hardware virtualization.

Can you validate the next nightly build works as expected ?

**Comment by hramosmo** [comment]
OK, it now detects Docker as the Vmsystem "Docker", but it still fails to assign the correct UUID — it continues to use the host's UUID instead of Docker's. Interestingly, it does assign Docker's UUID to the container name. The result is that the GLPI server is unable to properly link the Docker instance listed in the host's inventory with the independently inventoried Docker container. I'm attaching the JSON files for both the Docker container and the VirtualBox VM.

[salida_docker.json](https://github.com/user-attachments/files/21504574/salida_docker.json)
[salida_virtualbox.json](https://github.com/user-attachments/files/21504575/salida_virtualbox.json)

**Comment by g-bougard** [comment]
Hi @hramosmo 

I agree it's not correct to have the same UUID.

Actually, when run in the container, GLPI-Agent looks for container UUID into the content of `/proc/1/cgroup`. Can you share this content for container ?

If this provides the same UUID than host. Do you know how we should first get it into the container ?

**Comment by g-bougard** [comment]
Just saw something weird, the UUID seen from host seems to be the name of the container.

**Comment by g-bougard** [comment]
Can you share the output of the following command run into the container ?
```
glpi-inventory --debug --debug --partial=hardware
```

This is to verify how name & uuid could be set in your context.

**Comment by hramosmo** [comment]
> Hi [@hramosmo](https://github.com/hramosmo)
> 
> I agree it's not correct to have the same UUID.
> 
> Actually, when run in the container, GLPI-Agent looks for container UUID into the content of `/proc/1/cgroup`. Can you share this content for container ?
> 
> If this provides the same UUID than host. Do you know how we should first get it into the container ?

The content of /proc/1/cgroup into the Docker conatiner is "0::/"

Here is the output for the command:

[salida_debug.json](https://github.com/user-attachments/files/21508193/salida_debug.json)

**Comment by hramosmo** [comment]
> > Hi [@hramosmo](https://github.com/hramosmo)
> > I agree it's not correct to have the same UUID.
> > Actually, when run in the container, GLPI-Agent looks for container UUID into the content of `/proc/1/cgroup`. Can you share this content for container ?
> > If this provides the same UUID than host. Do you know how we should first get it into the container ?
> 
> The content of /proc/1/cgroup into the Docker conatiner is "0::/"
> 
> Here is the output for the command:
> 
> [salida_debug.json](https://github.com/user-attachments/files/21508193/salida_debug.json)

The name of the Docker computer is that because /etc/hostname has this content....

**Comment by hramosmo** [comment]
I've been investigating, and it seems that starting from a certain Docker version, they switched to using cgroupv2, which means the method of retrieving the UID from /proc/1/cgroup no works anymore. I haven't found a way to obtain the UID from within the Docker container without performing additional steps before launching the container, so I can't find a global approach to the problem.

Additionally, in my case, the hostname happens to match the UID because I didn’t bother specifying a hostname for the Docker container, and by default it uses the UID. I seem to recall that somewhere in the agent’s code there was a function that generates a virtual UUID based on certain host data — am I correct? Could that be used in this case?

**Comment by hramosmo** [comment]
Another option is to use the information available in the mount points of the overlay2 storage. The UID we’re seeing is actually the short version of the container ID. In fact, if we run the command docker ps --no-trunc, we get the full UID of the Docker containers.

I’m not sure how the inventory process on the host retrieves the list of Docker containers, but maybe it could be modified to obtain the full UID. Then, inside the Docker container, we could use the mount point information to extract the UID from within. I don't know — just brainstorming some ideas.

**Comment by g-bougard** [comment]
Okay, the cgroupv2 switch problem talks to me. I still saw this kind of issue with other containerization technology. This also means we need to keep current processing as fallback in the case a cgroupv2 adapted method gives nothing good to support older computers using cgroupv1.

You are right about the virtual UUID, but the difficulty with it is it must be generated the same way on host and in the container.

In host, [Docker.pm module](https://github.com/glpi-project/glpi-agent/blob/develop/lib/GLPI/Agent/Task/Inventory/Virtualization/Docker.pm) is the one who lists docker containers. We use literally the following command to list containers:
```
docker ps -a --format "{{ID}}#=#=#{{Image}}#=#=#{{Ports}}#=#=#{{Names}}"
```

`#=#=#` string is an arbitrary field separator to help command output result parsing.

We get `ID` and we use it as UUID. For each line, we run `docker inspect {{Found-ID}}` to know container status. And that's it.

I think the output is not truncated when using `--format` option. Can you confirm in your case ?

Looking to your host inventory, I can see:
```
      "virtualmachines": [
         {
            "image": "mariadb:latest",
            "name": "ejemplo-docker-mariadb",
            "status": "running",
            "uuid": "bc5516ccff8b",
            "vmtype": "docker"
         }
      ]
```
It means our `docker ps -a --format ...` command output should looks like:
```
bc5516ccff8b#=#=#mariadb:latest#=#=#XYZ#=#=#ejemplo-docker-mariadb
```
Where XYZ is the ports data we don't use actually.

Can you share commands output you think we can use to find container UUID from the container ?

**Comment by hramosmo** [comment]
OK, Docker mounts internal storage paths into the container that include the full 64-character container ID. These are visible via /proc/self/mountinfo from within the container. If you want to continue using truncated id yo can use this command to find container UUID from the container (I believe this is the best approach in the case of cgroupv2):

`grep -aoE '/docker/containers/[0-9a-f]{64}' /proc/self/mountinfo | grep -oE '[0-9a-f]{64}' | head -n1 | cut -c1-12` 

As a last resort, you could use `||hostname` at the end of the command or the container name that was previously obtained, but that only works if the hostname hasn’t been customized — so I’m not sure it’s a good idea.


If you want to use full uid using `docker ps -a --no-trunc --format "{{.ID}}#=#=#{{.Image}}#=#=#{{.Ports}}#=#=#{{.Names}}"` you can use `grep -aoE '/docker/containers/[0-9a-f]{64}' /proc/self/mountinfo | grep -oE '[0-9a-f]{64}' | head -n1 `

The output using --no-trunc looks like this:
```
8372cd234a4e51a2f88415a8bb79b1a88b5ecae84052a94642fc9fe14ba29cfd#=#=#mariadb:latest#=#=#3306/tcp#=#=#ejemplo-docker-mariadb3
cbf10ec0710c5ab7161909382cbba8e65b844974fcd9f82097ceba8488a1c739#=#=#mariadb:latest#=#=##=#=#ejemplo-docker-mariadb2
bc5516ccff8b57f4266a75526e3ce023763029b70ef9687418e6ff1de6a3b128#=#=#mariadb:latest#=#=#3306/tcp#=#=#ejemplo-docker-mariadb

```
I hope this helps.

**Comment by g-bougard** [comment]
Hi @hramosmo 

thank you for your proposition.

I just pushed an update which should fix your last issue. Can you validate it works as expected ?

I choose to keep looking on short container ID as changing now to full would involve duplication of container as UUID would be changed.

In your case, you'll probably have to make some clean up.

**Comment by hramosmo** [comment]
Hi @g-bougard , It works as expected ;-)  

[salida_json_docker_ok.json](https://github.com/user-attachments/files/21526137/salida_json_docker_ok.json)

<img width="1003" height="430" alt="Image" src="https://github.com/user-attachments/assets/71ee22cc-5c2b-43a3-881e-e9a3bde7c887" />
<img width="990" height="593" alt="Image" src="https://github.com/user-attachments/assets/32b616cd-fb60-4330-bd12-9e5197e2da38" />

Thank you very much for your work!
