### ISSUE TITLE
TP-Link switches SNMP

### ISSUE THREAD

**Issue by adamcios** [glpi-project/glpi-agent#990]
I noticed a problem with the information collected by the GLPI agent and uploaded to GLPI from TP-Link switches via SNMP. Generally, the switches I have network devices configured with VLANs (VLAN IDs 100, 120, 150, 151, etc.).

The switch is scanned in a basic way and some information is visible (basic details), but there's no VLAN information or network port details (all ports show the same MAC address) thats why i cant see what computer is conected to the port. Errors from network ports aren't being retrieved either, serial numberfirmware version, POE status(enable/disable)or memory information.

This model T1700G-28TQ can be stucked.

Attached scan results snmpwalk  of several configured switches following suggestions from @g-bougard snmpwalk and the MIB from TP-LINK's website. 

[L2-tplinkMibs.zip](https://github.com/user-attachments/files/21506825/L2-tplinkMibs.zip)

[10.1.151.54-TP-Link-T1700G-28TQv3.0.walk.txt](https://github.com/user-attachments/files/21506850/10.1.151.54-TP-Link-T1700G-28TQv3.0.walk.txt)
[10.8.151.7-TP-Link-SG3428v2.0.walk.txt](https://github.com/user-attachments/files/21506846/10.8.151.7-TP-Link-SG3428v2.0.walk.txt)
[10.8.151.12-TP-Link-SG3428MP-v5.0.walk.txt](https://github.com/user-attachments/files/21506844/10.8.151.12-TP-Link-SG3428MP-v5.0.walk.txt)
[10.110.151.4-TP-Link-SX3016Fv1.20.walk.txt](https://github.com/user-attachments/files/21506848/10.110.151.4-TP-Link-SX3016Fv1.20.walk.txt)
[10.110.151.10-TP-Link-SG3452Pv3.30.walk.txt](https://github.com/user-attachments/files/21506849/10.110.151.10-TP-Link-SG3452Pv3.30.walk.txt)
[10.110.151.17-TP-Link-SG3452v1.20.walk.txt](https://github.com/user-attachments/files/21506845/10.110.151.17-TP-Link-SG3452v1.20.walk.txt)
[192.168.0.51-TP-Link-SG3424-v2.0-oldermodel.walk.txt](https://github.com/user-attachments/files/21506847/192.168.0.51-TP-Link-SG3424-v2.0-oldermodel.walk.txt)
[L2-tplinkMibs.zip](https://github.com/user-attachments/files/21506851/L2-tplinkMibs.zip)

**Comment by g-bougard** [comment]
Hi @adamcios 

thank you for all the snmpwalk outputs and mibs.

Here is a first TpLink MibSupport module version: [TpLink-v1.zip](https://github.com/user-attachments/files/21514990/TpLink-v1.zip)

Can you unzip the included `TpLink.pm` perl module under the `lib/GLPI/Agent/SNMP/MibSupport` folder of your GLPI-Agent installation ? And test it ?

This first version should still provide mode integrated datas:
 - serialnumber for recent devices 
 - only for the SG3424 older model, I set serial to the mac address string with dash as separator I found
 - firmware and hardware version

Can you still check if serialnumbers are the expected ones ?

For the older SG3424, do you know what's the serialnumber ? If this is just the `30-B5-C2-62-04-EC` string, we are still good.

**Comment by adamcios** [comment]
serial number old model is 214C377000236 but i dont know if it is in firmware as information in old version switches dont show it even in gui. mac adress has been completed in serial number :)it starts working :)

![Image](https://github.com/user-attachments/assets/4973e4d7-d669-4a83-bf38-cac724edae2f)

<img width="610" height="336" alt="Image" src="https://github.com/user-attachments/assets/221bad9d-f335-4594-aec8-a67a0817918e" />

**Comment by g-bougard** [comment]
Hi @adamcios 

I can confirm you the S/N is not available anywhere into SNMP walk data. So the best is still to keep the mac address string as it can be physically found nead S/N.

> ... (all ports show the same MAC address) ...

About this point, I can confirm this is what says SNMP walk. That's effectively weird, but we can't do anything if this is the way that devices are designed.

**Comment by adamcios** [comment]
maybe u right. wchich oid glpi-agent expect information about mac on port? i will send to tp-link info...

**Comment by g-bougard** [comment]
Actually, mac address is read walking into standard `ifPhysAddress` (`.1.3.6.1.2.1.2.2.1.6`) OID.

Anyway, do you have any UI showing other mac is used on each interface ?

**Comment by adamcios** [comment]
Yes. i have such ports

port 12 mac 18-03-73-23-5E-F5
port 15 mac E0-BB-9E-44-01-34
port 18 mac 08-00-37-88-90-68
port 19 mac 00-1C-23-D1-BD-57
port 15 and 19 was in through last snmwalking -

another port are availble in new scan 

[192.168.0.51-TP-Link-SG3424-oldermodel.walk.txt](https://github.com/user-attachments/files/21547814/192.168.0.51-TP-Link-SG3424-oldermodel.walk.txt)

In UI i have some info :

<img width="660" height="467" alt="Image" src="https://github.com/user-attachments/assets/c5794f70-371c-4ad2-a7d8-b4175138fee0" />

<img width="601" height="303" alt="Image" src="https://github.com/user-attachments/assets/c29e4c7a-3aa6-472e-bc8a-930075ef77a5" />

<img width="652" height="334" alt="Image" src="https://github.com/user-attachments/assets/dc75f3a3-bedb-46e5-a98c-78b3f748321b" />

<img width="959" height="565" alt="Image" src="https://github.com/user-attachments/assets/b6606b4c-3dd8-4483-aa58-14d1180b9228" />

Remember that this model SG3424 is very old ( 2012 almost) other are newer :)

**Comment by g-bougard** [comment]
These MAC addresses are the seen MAC address for a remote device, not the MAC address set on the port. And they appear as is in glpi-agent inventory.

**Comment by adamcios** [comment]
the mac address on port is dynamically set (reading from communication ) depending on the connected device. I don't have permanently set (static) MAC addresses on the port. i want to know what remote device is connect to the port.  In GLPI i dont see it . 

<img width="1537" height="712" alt="Image" src="https://github.com/user-attachments/assets/a36641d5-5edd-4e76-87ec-f7dcdef70716" />

**Comment by g-bougard** [comment]
As only remote device mac address is discovered by glpi-agent, you have to also inventory remote devices. If the MAC address is not known in GLPI, only the connected status will appear.

If you can't inventory remote devices, try maybe to add device manually setting the expected mac address on one port.

**Comment by g-bougard** [comment]
Anyway, about the proposed module, did you make all required tests with all the TP-Link devices ? And so do you see any other critical problem ?

**Comment by adamcios** [comment]
the serial number looks correct
but the ip number in older model for 4 example we look bad . 
i found info in internet  that in many cases in TPlink mac adres (hexadecimal) is stored in snmp as decimal so 
port 12 mac 18-03-73-23-5E-F5 24.3.115.35.94.245  
port 15 mac E0-BB-9E-44-01-34 224.187.158.68.1.52
port 18 mac 08-00-37-88-90-68 8.0.55.136.144.104
port 19 mac 00-1C-23-D1-BD-57 0.28.35.209.189.87

grep 0.28.35.209.189.87 192.168.0.51-TP-Link-SG3424-oldermodel.walk.txt

<img width="1118" height="663" alt="Image" src="https://github.com/user-attachments/assets/e4a25c90-d320-456d-9377-41e5cba565a7" />

in this old i use only default vlan 1.  but i have not configured vlan id 100, 110 , 150, 151, 170, 171

in newer tplink i check also this information 
grep 228.185.122.114.200.201 10.110.151.17-TP-Link-SG3452v1.20.walk.txt i hve vlan id number default 1 and 100, 101,120,121,151,152,160, 161

<img width="1079" height="196" alt="Image" src="https://github.com/user-attachments/assets/a3c1ebb1-b178-4862-b6c3-8d17b51e34a8" />

i saw that  base OID .1.3.6.1.2.1.17.7.1.2.2.1.2  (Q-BRIDGE-MIB::dot1qTpFdbPort) has info about VLAN (decimail). and six decimal mac address 
example
.1.3.6.1.2.1.17.7.1.2.2.1.2.100.228.185.122.114.200.201 = INTEGER: 8 
base OID .1.3.6.1.2.1.17.7.1.2.2.1.2     VLAN 100    MAC: 228 = E4. 185 = B9. 122 = 7A, 114 = 72. 200 = C8. 201 = C9 (e4:b9:7a:72:c8:c9) , port   = INTEGER: 8
sometimes in other place we should check if vlan really exist but im looking for it  :) 
perhaps this help more

**Comment by g-bougard** [comment]
Hi,

I don't understand the problem with MAC address. Actually, the MAC is extracted from, for example:
<img width="596" height="21" alt="Image" src="https://github.com/user-attachments/assets/59eae44e-c1d7-434f-bf3a-8d669fd04c92" />

The decimal parts from OID is just a key from SNMP point of view and permits to have a unique key. As we have OID reporting the MAC, we don't need to extract it from that key. Nothing guarantee the manufacturer won't change key using another scheme in the future.

For the ip number on the older, can you explain what's wrong ?

**Comment by adamcios** [comment]
no it `s not extracted correct. on the switch in glpi  i see only one MAC address usually its mac address  of the switch.  look on the file this OID - .1.3.6.1.2.1.2.2.1.6 has the same mac address as switch mac address. every scan has the same info
switch 10.110.151.17

<img width="1539" height="774" alt="Image" src="https://github.com/user-attachments/assets/7e64bcff-2360-40a4-b559-38fe85be182f" />
and 
switch 192.168.0.51

<img width="1574" height="656" alt="Image" src="https://github.com/user-attachments/assets/06ec5fe7-a79f-4b85-9787-04bbbfb9ad10" />

and column vlan doesnt show info about what vlan is on the port and mac adress is duplicated on every port but its not true. 
port 49 is connected with switch 10.110.151.4 on port 2 mac adres this switch is E4-FA-C4-9B-02-02 228.250.196.155.2.2 and it should be hub i think. to switch 10.110.151.4 - i have all network device and computers and printer inventored in glpi with right mac address. and my dream is correlate information switch with switch , computer, printers etc..

switch 192.168.0.51 - 

<img width="829" height="365" alt="Image" src="https://github.com/user-attachments/assets/09cedbda-1d32-4a6d-829a-a36988791c24" />

and switch 10.110.151.17

<img width="828" height="706" alt="Image" src="https://github.com/user-attachments/assets/fe363daa-c075-4b7f-9f19-f0c19381e272" />

**Comment by adamcios** [comment]
sorry for grep - its not this oid .1.3.6.1.2.1.2.2.1.6 . but the info in GLPI is stil the same and i dont have mac address on ports.  if we grep this .1.3.6.1.2.1.17.4.3.1.1. in the file we have mac address but we dont have port. 
OID.1.3.6.1.2.1.17.4.3.1.1.VLAN 1.MAC:100.0.106.94.34.74 = Hex-STRING: 64 00 6A 5E 22 4A 

Anyway i dont have info in glpi in switch  ports stil have switch mac adres.

**Comment by adamcios** [comment]
sorry for grep - its not this oid .1.3.6.1.2.1.2.2.1.6 .  but  .1.3.6.1.2.1.17.4.3.1.1
But in your sugestion in such  oid 
.1.3.6.1.2.1.17.4.3.1.1.1.100.0.106.94.34.74 = Hex-STRING: 64 00 6A 5E 22 4A 
we have only
MAC: 64:00:6A:5E:22:4A
VLAN (FDB‑ID): 1 — the first index element before the 6 MAC bytes
Port: not in this OID 

<img width="1514" height="771" alt="Image" src="https://github.com/user-attachments/assets/10d935e2-23cc-4d7b-9f7f-0d5693bcffea" />

Anyway i dont have info in glpi. in switch ports stil have switch mac adres.

**Comment by g-bougard** [comment]
Hi @adamcios 

I'm sorry, but I don't understand what problem you think we can fix.

Actually, as you can see, SNMP walk tells ports have the same MAC address. Have you any clue for me to know each port has another MAC address ? Can you provide a list giving the real MAC address on each port ?

`.1.3.6.1.2.1.17.4.3.1.1` is an OID we use to find connected devices to a vlan. Don't focus on it, I took it as an example to explain the following numbers are a key to identify related values.

Have you also any clue telling me what should be set as IP on ports ? Should it be the same IP than the one on VLAN 1 ? Can you provide a list giving the real IP on each port ?

**Comment by adamcios** [comment]
One more time on old TP-link SG3424
Real 4 port example and mac address connected devices 
**port 12** mac 18-03-73-23-5E-F5         decimal 24.3.115.35.94.245
**port 15** mac E0-BB-9E-44-01-34        decimal 224.187.158.68.1.52
**port 18** mac 08-00-37-88-90-68        decimal 8.0.55.136.144.104
**port 19** mac 00-1C-23-D1-BD-57       decimal 0.28.35.209.189.87
grep every mac in decimal value from file 
grep 0.28.35.209.189.87 192.168.0.51-TP-Link-SG3424-oldermodel.walk.txt

<img width="1118" height="669" alt="Image" src="https://github.com/user-attachments/assets/f0e4f4db-2b26-4f29-9e1d-b3abc9682943" />

1 - vlan and mac , 2 - port number.

screen from this TPLINK in glpi : 

<img width="1531" height="732" alt="Image" src="https://github.com/user-attachments/assets/f5236b84-bfd9-42ef-9b24-ab97565bcf0b" />

if u want i can check more other switches with real mac addresses connected to ports comprare to snmpwalk files i sended

**Comment by adamcios** [comment]
@g-bougard  
My initial explanation was a bit chaotic because I misunderstood the "Network ports" table in GLPI>Network devices>switchname. Under the "Mac address" column, I expected to see the MAC address of the computer connected to that port . I was looking in GLPI for the MAC address that appears in the snmpwalk scan and the switch’s UI (e.g., on a specific port). GLPI only shows in column "connected to" mac adres equipment which are inwentoried not everything. my mistake

Topic 2

In version 192.168.0.51-TP-Link-SG3424-oldermodel.walk.txt, I get information about VLANs on the port :
 
<img width="365" height="579" alt="Image" src="https://github.com/user-attachments/assets/c1a91f73-577a-4812-9ca0-987f499c901c" />

i send you one more file with more connected devices 10.110.151.7-TP-Link-SG3452.walk.txt

and this newer model 10.110.151.7-TP-Link-SG3452.walk.txt dont show list of vlans on ports using command glpi-netinventory --file=10.110.151.7-TP-Link-SG3452.walk.txt

[10.110.151.7-TP-Link-SG3452.walk.txt](https://github.com/user-attachments/files/21680842/10.110.151.7-TP-Link-SG3452.walk.txt)

<img width="401" height="459" alt="Image" src="https://github.com/user-attachments/assets/fa67a94d-412c-4d8b-b724-6a40e0475b68" />

maybe info about vlans are moved to private MIB.   i cant found info about VLANS in public MIB 1.3.6.1.2.1.17.7.1.4.3.1.2 like in old models.

**Comment by g-bougard** [comment]
Hi @adamcios 

have you something to share about the current VLAN configuration on this device ? I can't guess what to search without help.

**Comment by adamcios** [comment]
List o Vlans 10.110.151.7

<img width="954" height="680" alt="Image" src="https://github.com/user-attachments/assets/bdc75843-3960-42aa-a5ef-51df7791af7d" />

i found and check some info like in table  maybe it help in resarch 

<html><head></head><body><h1>VLAN OID mapping — <strong>Public (IETF)</strong> ↔ <strong>TP-Link Legacy</strong> ↔ <strong>TP-Link Newer</strong></h1>

Function | Public MIB (IETF) | TP-Link old (SG3424, 11863.1…) | TP-Link newer (SG3452, 11863.6…) | Notes
-- | -- | -- | -- | --
VLAN ID (list/indices) | dot1qVlanFdbId 1.3.6.1.2.1.17.7.1.4.3.1.5.<VID> (or just use indices of Name/Egress/Untagged tables) | 1.3.6.1.4.1.11863.1.1.3.3.1.1.2.1.1.<VID> | 1.3.6.1.4.1.11863.6.14.1.2.1.1.1.<VID> | Often, listing the indices of Name/Egress/Untagged is enough.
VLAN name | dot1qVlanStaticName 1.3.6.1.2.1.17.7.1.4.3.1.1.<VID> | …11863.1.1.3.3.1.1.2.1.2.<VID> | …11863.6.14.1.2.1.1.2.<VID> | TP-Link typically returns ASCII as Hex-STRING.
Egress members (all members) | dot1qVlanStaticEgressPorts 1.3.6.1.2.1.17.7.1.4.3.1.2.<VID> | Tagged: …11863.1.1.3.3.1.1.2.1.5.<VID> + Untagged: …11863.1.1.3.3.1.1.2.1.4.<VID> | Tagged: …11863.6.14.1.2.1.1.3.<VID> + Untagged: …11863.6.14.1.2.1.1.4.<VID> | Public = bitmaps; Private = ASCII lists (e.g., 1/0/1-48,1/0/50).
Untagged members | dot1qVlanStaticUntaggedPorts 1.3.6.1.2.1.17.7.1.4.3.1.4.<VID> | …11863.1.1.3.3.1.1.2.1.4.<VID> | …11863.6.14.1.2.1.1.4.<VID> | In public MIB, determine untagged from the bitmap.
PVID per port | dot1qPvid 1.3.6.1.2.1.17.7.1.4.5.1.1.<bridgePort> | …11863.1.1.5.1.1.<ifIndex> | …11863.6.21.1.3.3.1.1.<ifIndex> | Public index = bridgePort → map via dot1dBasePortIfIndex; Private uses ifIndex directly.
bridgePort → ifIndex map | dot1dBasePortIfIndex 1.3.6.1.2.1.17.1.4.1.2.<bridgePort> | — | — | Needed with dot1qPvid and the public VLAN bitmaps.
FDB in VLAN (MAC → port) | dot1qTpFdbPort 1.3.6.1.2.1.17.7.1.2.2.1.2.<VID>.<MAC> | …11863.1.1.3.2.3.2.2.1.{1..5}.<MAC> (MAC, VLAN, port) | …11863.6.10.1.1.1.1.{1..4}.<MAC> (MAC, VLAN, port) | For MAC↔port↔VLAN correlation (complements membership tables).

</body></html>

but its probably needed confirmation by specialist 

below is screen of vlans 192.168.0.51.... old model ( but only default vlan is used for that mometn ) 

<img width="1041" height="461" alt="Image" src="https://github.com/user-attachments/assets/bbf5d2fd-dcb6-4d22-8187-b844d6c9a05c" />

**Comment by g-bougard** [comment]
Hi @adamcios 

but as your screenshot shows, VLAN 100 to 171 has no member: this means they are no linked to any port.

This is exactly what reports GLPI-Agent. And this is exactly what I see in standard OIDs and also in private ones.

So we are still okay with the old model.

For the newer model, I don't see standard OIDs, but I find private ones for 10.110.151.7. Tp-Link is not fair on that case. This won't be easy to support.

**Comment by g-bougard** [comment]
Can you update your TpLink module with this one ?
[TpLink-v2.zip](https://github.com/user-attachments/files/21720410/TpLink-v2.zip)

It should report VLAN as expected for newer devices.

**Comment by adamcios** [comment]
i update this file in one firm:

1. i check this SG3452 all switch has on ports info about VLAN (T and U). Briliant. another problem on that model are abscence everything on connected ports. Some computers automaticly shows on the port but some not. Port shows info about I/O bytes , Vlan, Alias, and even shows Internal status and last connection but "connected to" is empty. 
Every devices from list below on this ports is present in GLPI but on switch dont see it

port 7  94:DD:F8:2F:61:77  Printer DR21
port 10 40:B0:34:24:59:FC  Printer DR11
port 11 90:B1:1C:71:7E:BE  Computer SP89
port 15 18:03:73:1E:E7:1C  Computer SP30
port 16 E4:54:E8:95:E8:CB  Computer SP041
port 24 D8:9E:F3:47:E0:3B  Computer SP226
port 25 A8:B1:3B:BC:A9:EA  Printer DR03
port 37 48:4D:7E:E2:1E:93  Computer SP199

new snmpwalk file 
[10.110.151.7-TP-Link-SG3452v1.20.walk.0813_1.txt](https://github.com/user-attachments/files/21752832/10.110.151.7-TP-Link-SG3452v1.20.walk.0813_1.txt)

2. Check this 2  switches SX3016F ( about VLANS ) one is ok and second is partial only ( dont understand why). "Conencted to" i join mannualy
i send u 2 new scans of this two switches one has every port VLAN info visable - sekond only one port . 

[10.110.151.4-TP-Link-SX3016Fv1.20.walk.0813_1.txt](https://github.com/user-attachments/files/21752858/10.110.151.4-TP-Link-SX3016Fv1.20.walk.0813_1.txt)

[10.110.151.5-TP-Link-SX3016Fv1.20.walk.0813_1.txt](https://github.com/user-attachments/files/21752862/10.110.151.5-TP-Link-SX3016Fv1.20.walk.0813_1.txt)

3. i check switch SG3452P VLANS perfectly well but problem like in SG3452 ( no devices connected but they exist in glpi assets). the same situation like in SG3452
 
port 5   18:66:DA:49:86:3A  Computer sp152
port 8   28:29:86:86:AC:CD  UPS2
port 6   28:29:86:86:AE:0A  UPS1
port 3   30:8D:99:A9:70:46  Printer DR09
port 11  40:F8:DF:63:85:3C  Printer DR66


[10.110.151.10-TP-Link-SG3452Pv3.30.walk.0813_1.txt](https://github.com/user-attachments/files/21752883/10.110.151.10-TP-Link-SG3452Pv3.30.walk.0813_1.txt)

I just hope that TP-LINK sticks to its private OIDs and doesn't invent new ones for each switch model
To sum up - VLANs are reading better and better from snmp.

**Comment by adamcios** [comment]
maybe its important information that we have port seurity enalbed and when i check info in UI TPlink about port i get such table - maybe it will be diffrent OID
SG3452   (look at cloumn Type and Aging status )

<img width="1306" height="858" alt="Image" src="https://github.com/user-attachments/assets/d82afd1c-0327-48fd-b198-afbeeecad153" />
and 3452p (look at cloumn Type and Aging status )

<img width="1021" height="827" alt="Image" src="https://github.com/user-attachments/assets/b439dbff-dd9f-4ab2-87ee-55acea5a801f" />

**Comment by g-bougard** [comment]
Hi @adamcios 

about point 1 and 3, they are all static mac address for the first point, where port 6 & 8 are dynamic on the second and the MAC appears for them in CONNECTION node. Static mac address doesn't mean the device is really connected and up, this is a device configuration. Imagine the remote device was moved to another network and the configuration on that TP-Link device not removed... doesn't it mean we have to keep it connected to the TP-Link even if it appears connected somewhere else ? Of course, not.

The question is really how to know if the remote device is really connected in that case of static mac configured.

About point 2, I'm getting at least one VLAN for each port checking the 2 walks. Where do you see a problem ?

**Comment by g-bougard** [comment]
Well, I found our code only accept "3" as mac status which means "learned", but I can see in specs that "5" means "the value of the corresponding instance of dot1dTpFdbAddress is also the value of an existing instance of dot1dStaticAddress."... And so if I change the code to also accept this status, I can see a connection node with the expected mac where you have a static address.

I'll make some tests and include the fix if it seems okay.

**Comment by g-bougard** [comment]
Hi @adamcios 

I pushed the last module version and included the fix to accept `5` as connected mac status.

You can use the next nightly build or you can manually apply this last patch:
```diff
diff --git a/lib/GLPI/Agent/Tools/Hardware.pm b/lib/GLPI/Agent/Tools/Hardware.pm
index 222f8813e..55318abfc 100644
--- a/lib/GLPI/Agent/Tools/Hardware.pm
+++ b/lib/GLPI/Agent/Tools/Hardware.pm
@@ -1035,7 +1035,8 @@ sub _getKnownMacAddresses {
             next unless $mac;
             # Assume mac status is learned(3) if not found
             my $status = $macstatus && defined($macstatus->{$suffix}) && $macstatus->{$suffix} =~ /(\d+)/ ? int($1) : 3;
-            next unless $status == 3;
+            # Accepted status could be 3 for "learned" and 5 for "mgmt" (mac also setup as static in the device)
+            next unless $status == 3 || $status == 5;
             push @{$results->{$interface_id}}, $mac;
         } else {
             my @bytes = split(/\./, $suffix);

```

I won't be available for the next 2 weeks, so if you see other issues, please open a new one referencing this one.

A last note, don't expect to see a connection on a port in GLPI if glpi-agent detects more than one mac address.

**Comment by adamcios** [comment]
testing and still have problem with place where port security is enabled
